name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 black mypy bandit

    - name: Lint com flake8
      run: flake8 app/

    - name: Verificação de formatação com black (não bloqueia)
      run: black --check app/ || true

    - name: Verificação de tipos com mypy
      run: mypy app/

    - name: Testes com pytest
      run: pytest app/
